task :default => :turn

task :turn do
  base_dir = File.join(File.dirname(__FILE__))
  input_dir = File.join(base_dir, 'input')
  output_dir = File.join(base_dir, 'output')
  sh "sushi #{base_dir}"
end
