task :default => :turn

desc 'Turn all steps to generate IG/Profile'
task :turn do
  base_dir = File.join(File.dirname(__FILE__))
  input_dir = File.join(base_dir, 'input')
  output_dir = File.join(base_dir, 'output')
  sh "sushi #{base_dir}"
  sh "#{base_dir}/_updatePublisher.sh"
  sh "#{base_dir}/_genonce.sh"
end
