name: Turn Sushi table.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  OUTPUT_DIR: ../doc

jobs:
  turn:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0'] #, '3.1']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
    # uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        working-directory: JP_CORE_EXPERIMENTAL
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Set up npm
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        cache: 'npm'
        cache-dependency-path: JP_CORE_EXPERIMENTAL/package-lock.json
    - name: Setup Sushi
      run: npm install -g fsh-sushi
    - name: Turn the table
      working-directory: JP_CORE_EXPERIMENTAL
      run: bundle exec rake
    # - name: Check broken links.
    #   working-directory: JP_CORE_EXPERIMENTAL
    #   run: bundle exec rake check
