# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Turn Sushi table.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  turn:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0'] #, '3.1']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        working-directory: JP_CORE_EXPERIMENTAL
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Set up Sushi
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        cache: 'npm'
        working-directory: JP_CORE_EXPERIMENTAL
    - name: Turn the table
      working-directory: JP_CORE_EXPERIMENTAL
      run: bundle exec rake
    - name: Chek broken links.
      working-directory: JP_CORE_EXPERIMENTAL
      run: bundle exec rake check
